# Generated by Django 5.1.4 on 2024-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('workplace', models.CharField(max_length=200, verbose_name='Workplace')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('messenger_contact', models.CharField(help_text='Telegram username or WhatsApp number', max_length=100, verbose_name='Telegram/WhatsApp Contact')),
                ('academic_degree', models.CharField(choices=[('PHD_ECON', '(PhD), Economics'), ('PHD_PED', '(PhD), Pedagogy'), ('PHD_TECH', '(PhD), Technical Sciences'), ('DSC_ECON', '(DSc), Economics'), ('DSC_PED', '(DSc), Pedagogy'), ('DSC_TECH', '(DSc), Technical Sciences')], max_length=20, verbose_name='Academic Degree')),
                ('academic_title', models.CharField(choices=[('DOCENT', 'Docent'), ('PROFESSOR', 'Professor')], max_length=20, verbose_name='Academic Title')),
                ('orcid', models.CharField(blank=True, help_text='ORCID identifier', max_length=20, verbose_name='ORCID Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
