# Generated by Django 5.1.4 on 2025-01-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='academic_title',
            field=models.CharField(choices=[('DOCENT', 'Docent'), ('PROFESSOR', 'Professor'), ('ACADEMIC', 'Academic')], max_length=20, verbose_name='Academic Title'),
        ),
    ]
