# Generated by Django 5.1.4 on 2025-01-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_academic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='academic_degree',
            field=models.CharField(blank=True, choices=[('PHD_ECON', '(PhD), Economics'), ('PHD_PED', '(PhD), Pedagogy'), ('PHD_TECH', '(PhD), Technical Sciences'), ('DSC_ECON', '(DSc), Economics'), ('DSC_PED', '(DSc), Pedagogy'), ('DSC_TECH', '(DSc), Technical Sciences')], max_length=20, null=True, verbose_name='Academic Degree'),
        ),
        migrations.AlterField(
            model_name='author',
            name='academic_title',
            field=models.CharField(blank=True, choices=[('DOCENT', 'Docent'), ('PROFESSOR', 'Professor'), ('ACADEMIC', 'Academic')], max_length=20, null=True, verbose_name='Academic Title'),
        ),
    ]
