# Generated by Django 5.1.4 on 2025-01-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_academic_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='messenger_contact',
        ),
        migrations.AddField(
            model_name='author',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Position or level of education'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram_contact',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=100, null=True, verbose_name='Telegram Contact'),
        ),
        migrations.AddField(
            model_name='author',
            name='whatsapp_contact',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=100, null=True, verbose_name='WhatsApp Contact'),
        ),
    ]
