# Generated by Django 5.1.4 on 2024-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_prefers_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefers_dark_mode',
            field=models.BooleanField(default=False, verbose_name='Prefer Dark Mode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('secretary', 'Secretary'), ('deputy_editor', 'Deputy Editor'), ('admin', 'Admin')], default='author', max_length=20, verbose_name='Role'),
        ),
    ]
