# Generated by Django 5.1.4 on 2025-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_prefers_dark_mode_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completion_step',
            field=models.CharField(choices=[('registration', 'Initial Registration'), ('personal_info', 'Personal Information'), ('workplace_info', 'Workplace Information'), ('contact_info', 'Contact Information'), ('academic_info', 'Academic Information'), ('completed', 'Profile Completed')], db_index=True, default='registration', max_length=20, verbose_name='Profile Completion Step'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
