# Generated by Django 5.1.4 on 2024-12-20 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original_file',
            field=models.FileField(help_text='Accepted file types: .txt, .doc, .docx, .odt', upload_to='article_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'doc', 'docx', 'odt'])], verbose_name='Original Article File'),
        ),
    ]
