# Generated by Django 5.1.4 on 2024-12-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_slug'),
        ('categories', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='categories.category', verbose_name='Direction'),
        ),
    ]
