# Generated by Django 5.1.4 on 2025-01-13 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anti_plagiarism_certificate',
            field=models.FileField(blank=True, help_text='Accepted file types: .pdf', null=True, upload_to='anti_plagiarism_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Anti-Plagiarism Certificate'),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='List of references'),
        ),
    ]
