# Generated by Django 5.1.4 on 2025-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_anti_plagiarism_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='review_date',
        ),
        migrations.AddField(
            model_name='article',
            name='revision_requested_date',
            field=models.DateTimeField(blank=True, help_text='Article returned for editing date', null=True, verbose_name="Tahrir so'ralgan sana"),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Jarayonda'), ('REVISION_REQUESTED', 'Tahrir uchun qaytarilgan'), ('ACCEPTED', 'Qabul qilingan'), ('REJECTED', 'Rad etilgan'), ('PUBLISHED', 'Chop etilgan')], default='SUBMITTED', max_length=20, verbose_name='Status'),
        ),
    ]
