# Generated by Django 5.1.4 on 2025-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='revision_requested_date',
            field=models.DateTimeField(blank=True, help_text='Article returned for editing date', null=True, verbose_name='Tahrir so‘ralgan sana'),
        ),
    ]
