# Generated by Django 5.1.4 on 2025-02-28 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_revision_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='original_file',
            field=models.FileField(blank=True, help_text='Accepted file types: .txt, .doc, .docx, .odt', upload_to='article_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'doc', 'docx', 'odt'])], verbose_name='Original Article File'),
        ),
    ]
