# Generated by Django 5.1.4 on 2025-03-24 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_original_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_certificate',
            field=models.FileField(blank=True, help_text='Accepted file types: .pdf', null=True, upload_to='article_publication_certs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificate of Article Publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter keywords separated by commas', null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='revised_file',
            field=models.FileField(blank=True, help_text='Accepted file types: .pdf', null=True, upload_to='article_revisions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Revised Article File'),
        ),
    ]
