# Generated by Django 5.1.4 on 2025-03-04 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_original_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Maqola ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='article',
            name='deputy_chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_chief_articles', to=settings.AUTH_USER_MODEL, verbose_name="Bosh muharrir o'rinbosari"),
        ),
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_articles', to=settings.AUTH_USER_MODEL, verbose_name='Muharrir'),
        ),
        migrations.AddField(
            model_name='article',
            name='final_file',
            field=models.FileField(blank=True, help_text='Accepted file types: .pdf', null=True, upload_to='final_articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Final Article File'),
        ),
        migrations.AddField(
            model_name='article',
            name='review_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqish muddati"),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_articles', to=settings.AUTH_USER_MODEL, verbose_name='Taqrizchi'),
        ),
        migrations.AddField(
            model_name='article',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_articles', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul kotib"),
        ),
        migrations.AlterField(
            model_name='article',
            name='revision_requested_date',
            field=models.DateTimeField(blank=True, help_text='Article returned for editing date', null=True, verbose_name="Tahrir so'ralgan sana"),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Qoralama'), ('SUBMITTED', 'Yuborilgan'), ('SECRETARY_REVIEW', "Mas'ul kotib tekshiruvida"), ('REVIEWER_REVIEW', 'Taqrizchi tekshiruvida'), ('EDITOR_REVIEW', 'Muharrir tekshiruvida'), ('DEPUTY_REVIEW', "Bosh muharrir o'rinbosari tekshiruvida"), ('REVISION_REQUESTED', 'Tahrir uchun qaytarilgan'), ('ACCEPTED', 'Qabul qilingan'), ('REJECTED', 'Rad etilgan'), ('PUBLISHED', 'Chop etilgan')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(max_length=30, verbose_name='Yangi holat')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('file', models.FileField(blank=True, null=True, upload_to='articles/history/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='articles.article', verbose_name='Maqola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_actions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Maqola tarixi',
                'verbose_name_plural': 'Maqola tarixi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('file', models.FileField(blank=True, null=True, upload_to='comments/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='Maqola')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
