# Generated by Django 5.1.4 on 2025-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_article_id_article_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='review_deadline',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SECRETARY_REVIEW', 'Secretary review'), ('REVIEWER_REVIEW', 'Reviewer review'), ('EDITOR_REVIEW', 'Editor review'), ('DEPUTY_REVIEW', 'Deputy editor review'), ('REVISION_REQUESTED', 'Returned for revision'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
    ]
