# Generated by Django 5.1.4 on 2025-03-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_article_review_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SECRETARY_REVIEW', 'Secretary review'), ('REVIEWER_REVIEW', 'Reviewer review'), ('EDITOR_REVIEW', 'Editor review'), ('DEPUTY_REVIEW', 'Deputy editor review'), ('REVISION_REQUESTED', 'Returned for revision'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published')], default='SUBMITTED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='articlehistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Oldingi holat'),
        ),
    ]
