# Generated by Django 5.1.4 on 2025-03-10 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='final_file',
        ),
        migrations.AlterField(
            model_name='article',
            name='revised_file',
            field=models.FileField(blank=True, help_text='Accepted file types: .pdf', null=True, upload_to='article_revisions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Final Article File'),
        ),
    ]
