# Generated by Django 5.1.4 on 2024-12-20 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Journal Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
        migrations.CreateModel(
            name='JournalVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.PositiveIntegerField(verbose_name='Volume Number')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journals.journal', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Journal Volume',
                'verbose_name_plural': 'Journal Volumes',
                'ordering': ['-year', '-volume_number'],
                'unique_together': {('journal', 'volume_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('issue_number', models.PositiveIntegerField(verbose_name='Issue Number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_issues/', verbose_name='Cover Image')),
                ('journal_file', models.FileField(blank=True, null=True, upload_to='journal_issues/', verbose_name='Journal File')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('start_page', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Start Page')),
                ('end_page', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='End Page')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='journals.journalvolume', verbose_name='Volume')),
            ],
            options={
                'verbose_name': 'Journal Issue',
                'verbose_name_plural': 'Journal Issues',
                'ordering': ['-publication_date', '-issue_number'],
                'unique_together': {('volume', 'issue_number')},
            },
        ),
    ]
