# Generated by Django 5.1.4 on 2024-12-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='journal',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='journal',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Journal Name'),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Journal Name'),
        ),
        migrations.AddField(
            model_name='journal',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Journal Name'),
        ),
    ]
