# Generated by Django 5.1.4 on 2024-12-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_description_en_journal_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalissue',
            name='number',
        ),
    ]
