# Generated by Django 5.1.4 on 2024-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_journal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalissue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
