# Generated by Django 5.1.4 on 2024-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_journalissue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalissue',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
