# Generated by Django 5.1.4 on 2025-03-04 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0012_article_article_id_article_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_value', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Ilmiy qiymati')),
                ('methodology', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Metodologiyasi')),
                ('practical_value', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Amaliy ahamiyati')),
                ('novelty', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Yangiligi')),
                ('recommendation', models.CharField(choices=[('ACCEPT', 'Qabul qilish'), ('MINOR_REVISION', 'Kichik tahrir talab qilinadi'), ('MAJOR_REVISION', 'Katta tahrir talab qilinadi'), ('REJECT', 'Rad etish')], max_length=20, verbose_name='Tavsiya')),
                ('comments_to_author', models.TextField(verbose_name='Muallif uchun izohlar')),
                ('comments_to_editor', models.TextField(blank=True, verbose_name='Muharrir uchun izohlar')),
                ('review_file', models.FileField(blank=True, null=True, upload_to='reviews/', verbose_name='Taqriz fayli')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Anonim taqriz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article', verbose_name='Maqola')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Taqrizchi')),
            ],
            options={
                'verbose_name': 'Taqriz',
                'verbose_name_plural': 'Taqrizlar',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'reviewer')},
            },
        ),
    ]
