# Generated by Django 5.1.4 on 2025-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments_to_author',
            field=models.TextField(blank=True, null=True, verbose_name='Muallif uchun izohlar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_to_editor',
            field=models.TextField(blank=True, null=True, verbose_name='Muharrir uchun izohlar'),
        ),
    ]
